// Generated by gencpp from file qqy_msgs/Carry.msg
// DO NOT EDIT!


#ifndef QQY_MSGS_MESSAGE_CARRY_H
#define QQY_MSGS_MESSAGE_CARRY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qqy_msgs
{
template <class ContainerAllocator>
struct Carry_
{
  typedef Carry_<ContainerAllocator> Type;

  Carry_()
    : grate()
    , star(0)
    , data()  {
    }
  Carry_(const ContainerAllocator& _alloc)
    : grate(_alloc)
    , star(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _grate_type;
  _grate_type grate;

   typedef int64_t _star_type;
  _star_type star;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::qqy_msgs::Carry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qqy_msgs::Carry_<ContainerAllocator> const> ConstPtr;

}; // struct Carry_

typedef ::qqy_msgs::Carry_<std::allocator<void> > Carry;

typedef boost::shared_ptr< ::qqy_msgs::Carry > CarryPtr;
typedef boost::shared_ptr< ::qqy_msgs::Carry const> CarryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qqy_msgs::Carry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qqy_msgs::Carry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qqy_msgs::Carry_<ContainerAllocator1> & lhs, const ::qqy_msgs::Carry_<ContainerAllocator2> & rhs)
{
  return lhs.grate == rhs.grate &&
    lhs.star == rhs.star &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qqy_msgs::Carry_<ContainerAllocator1> & lhs, const ::qqy_msgs::Carry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qqy_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qqy_msgs::Carry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qqy_msgs::Carry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qqy_msgs::Carry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qqy_msgs::Carry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qqy_msgs::Carry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qqy_msgs::Carry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qqy_msgs::Carry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d42e125daf9f6b149ddf8ecec0283ce3";
  }

  static const char* value(const ::qqy_msgs::Carry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd42e125daf9f6b14ULL;
  static const uint64_t static_value2 = 0x9ddf8ecec0283ce3ULL;
};

template<class ContainerAllocator>
struct DataType< ::qqy_msgs::Carry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qqy_msgs/Carry";
  }

  static const char* value(const ::qqy_msgs::Carry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qqy_msgs::Carry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string grate\n"
"int64 star\n"
"string data\n"
;
  }

  static const char* value(const ::qqy_msgs::Carry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qqy_msgs::Carry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grate);
      stream.next(m.star);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Carry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qqy_msgs::Carry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qqy_msgs::Carry_<ContainerAllocator>& v)
  {
    s << indent << "grate: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.grate);
    s << indent << "star: ";
    Printer<int64_t>::stream(s, indent + "  ", v.star);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QQY_MSGS_MESSAGE_CARRY_H
